name: Clarkâ€¢Online
favicon: null
layout_spectrum: 0.25108
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#3a3a3a'
    - '#fefefe'
    - '#616161'
    - '#85ea00'
  brandStrength: 0.25
  lightness: 0.239309
  saturation: 0.251645
  rhythmicContrast: 0.5
purpose:
  - name: null
    item: null
    url: null
